
name: Linux Build

on: push

jobs:
  build:
    name: Build on Ubuntu
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Build C Code
      run: |
        export MAILSYNC_DIR=$( cd $(dirname $0) ; pwd -P );
        export APP_ROOT_DIR="$MAILSYNC_DIR/../app"
        export APP_DIST_DIR="$APP_ROOT_DIR/dist"
        export DEP_BUILDS_DIR=/tmp/mailsync-build-deps-v2 # Note: also referenced in CMakeLists
        cmake .
        make
